# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20c5ce510247c2a5f71a46c22bc9f1480d811392dcfd51328d351dedd5735432a4484aa852c5949f071bb1e93ea37b7547003c8d81108caa13643bb65288de67

test:
  secret_key_base: 497aa9609d44b63ce25a11a31f9d8ea7021fc9cd89a36d8aacce4cba81f059e9611b06684d2e4bd1934ac33449f77067d5e46c7e6d98a0ef08190eeba5b1f11c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
